### ISSUE TITLE
Possible fd leak

### ISSUE THREAD

**Issue by m13253** [m13253/pofw#1]
I have observed "too many open files" error message after a few weeks' running.

There may be a file descriptor (fd) leak somewhere.

Still investigating.

**Comment by messyidea** [comment]
It seems that CloseRead and CloseWrite will not close the fd.

**Comment by m13253** [comment]
Thank you for your info.
Do you have any idea to fix it?

**Comment by messyidea** [comment]
Maybe using reference counting is a good way.
For tcp, init the reference counting to 2, once close a side, decrease 1, when reference counting become 0, close the conn.

**Comment by m13253** [comment]
I guess it's fixed now.
